In [20]:
import pandas as pd

In [26]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"], index=["X","Y","Z"])

In [27]:
df.head()

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [29]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [30]:
df

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [31]:
df.nunique

<bound method DataFrame.nunique of    A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9>

In [32]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [33]:
df['A'].unique()

array([1, 4, 7])